SMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

facultyapp/urls.py
from django.urls import path
from . import views

app_name = 'facultyapp'

urlpatterns = [
    path('', views.faculty_home, name='faculty_home'),
    path('', views.projecthomepage, name='projecthomepage'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('FacultyHomePage/', views.FacultyHomePage, name='FacultyHomePage'),
    path('logout/', views.logout, name='logout'),
    path('add_course/', views.add_course, name='add_course'),
    path('view_student_list/', views.view_student_list, name='view_student_list'),
    path('post_marks/', views.post_marks, name='post_marks'),
]

studentapp/urls.py
from django.urls import path

from . import views
app_name = 'studentapp'
urlpatterns = [
 path('student/',views.studentconsole,name='student'),
 path('StudentHomePage/',views.StudentHomePage,name='StudentHomePage'),
 path('view_marks/',views.view_marks,name='view_marks')
]

templates/Navbar/FacultyNavbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        .custom-navbar {
            background-color: #FFA07A; /* Change this to your desired color */
        }
        .custom-navbar .nav-link {
            color: Black; /* Ensure the text is visible */
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg custom-navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="">Faculty Blog Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">Add Course to Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:view_student_list' %}">View Student list</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:post_marks' %}">Add Marks</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tasks
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'facultyapp:faculty_home' %}">Faculty Blog Post</a></li>

          </ul>
        </li>
      </ul>
    </div>
    <ul class="navbar-nav ms-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-link">Welcome, {{ user.username }}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% block body %}

{% endblock %}

</body>
</html>

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        .custom-navbar {
            background-color: #28E4C4; /* Change this to your desired color */
        }
        .custom-navbar .nav-link {
            color: Black; /* Ensure the text is visible */
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg custom-navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student' %}">Add Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'randompagecall'%}">Random Number Generator</a></li>
            <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">Exceptional Handling</a></li>
            <li><a class="dropdown-item" href="{% url 'calculatorpagecall'%}">Calculator</a></li>
            <li><a class="dropdown-item" href="{% url 'datetimepagecall'%}">Date</a></li>
            <li><a class="dropdown-item" href="{% url 'add_task'%}">To-Do-List</a></li>
            <li><a class="dropdown-item" href="{% url 'upload_file'%}">Make a Chart</a></li>
            <li><a class="dropdown-item" href="{% url 'feedback'%}">Give Feedback</a></li>
            <li><a class="dropdown-item" href="{% url 'add_contact'%}">add_contact</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <ul class="navbar-nav ms-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-link">Welcome, {{ user.username }}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% block body %}

{% endblock %}

</body>
</html>

templates/Navbar/StudentNavbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        .custom-navbar {
            background-color: #FA8072; /* Change this to your desired color */
        }
        .custom-navbar .nav-link {
            color: Black; /* Ensure the text is visible */
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg custom-navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=""></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'studentapp:view_marks' %}">view_marks</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            STUDENT
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'Student' %">STUDENT</a></li>


          </ul>
        </li>
      </ul>
    </div>
    <ul class="navbar-nav ms-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-link">Welcome, {{ user.username }}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% block body %}

{% endblock %}

</body>
</html>